### ISSUE TITLE
Move away from requiring all users to run 'mcvirt' using sudo

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#11]
The current way of using the [mcvirt script](https://github.com/ITDevLtd/MCVirt/blob/master/source/usr/bin/mcvirt) is to sudo the command.

However, this requires a sudo rule to be setup and for the end-users to remember to run the script using sudo.

The method of determining the username will need to be changed in the [Auth class](https://github.com/ITDevLtd/MCVirt/blob/master/source/usr/lib/mcvirt/auth.py#L48)

One alternative would be to use setuid

**Comment by MatthewJohn** [comment]
It may be better to create an mcvirt daemon running as a user with fewer privileges (ie not root), then use dbus to control it.

dbus is a good technology to choose for IPC, because it has excellent library support, and I think will tell you the user on the other end in a trustworthy way.

You could also have the mcvirt "daemon" only start when there's something to actually do, using socket activation (when systemd comes along in Ubuntu 16.04)

**Comment by s-knibbs** [comment]
The daemon idea sounds like the best idea but also involves the most work. It would also be nice to have a single way of communicating to the daemon on the local and remote nodes. AFAIK, d-bus only works locally.

The main difficulty with this approach is how to handle the authentication of the client users in the daemon.
