### ISSUE TITLE
Fix PEP 8 errors in code

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#12]
There are currently a lot of PEP 8 warnings in the code base.

Once the code is aligned with this coding standard, [the development guide](https://github.com/ITDevLtd/MCVirt/blob/master/Documentation/Development.rst) will need updating to explain that changes need to conform to this coding standard.

The PEP 8 checker will need adding to the Jenkins build

**Comment by s-knibbs** [comment]
There is a tool that should automatically fix many of these errors:
https://pypi.python.org/pypi/autopep8/1.1.1

**Comment by MatthewJohn** [comment]
Running: ``autopep8 --in-place --indent-size 4 --max-line-length 100 -aa  `find -type f -name '*.py'``` decreases the number of issues from 582 to 43
