### ISSUE TITLE
Create dummy network for VMs during unittest

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#130]
The unit tests currently rely on the existence of a 'Production' network on the nodes that it runs on.

It would be good if it created a dummy network adapter on the machine and add a test network for use in the unit tests

**Comment by joe-singleton-itdev** [comment]
The following will create a dummy network interface and give it an IP address:
```
$ ip tuntap add dev <name> mode tap
$ ip addr add <IP address>/<net mask> dev <name>
```
but will need to be run as root.

**Comment by MatthewJohn** [comment]
see https://jamielinux.com/docs/libvirt-networking-handbook/appendix/dummy-interface-on-debian.html

**Comment by MatthewJohn** [comment]
This was tested in the above commits and, although I could add the adapter etc, libvirt threw an exception:
```
