### ISSUE TITLE
Fix issues with cluster of greater than 2 nodes

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#151]
We should test all functionality and ensure that it works with cluster of more than 2 nodes

**Comment by joe-singleton-itdev** [comment]
Things to test could include:
* Removing a node from the cluster and checking that the appropriate VMs, SSL certificates, cluster users etc… are removed from *all* the nodes left in the cluster
* Creating/deleting VMs (with local and DRBD storage)
* Creating/deleting users
* Creating/deleting networks
* Managing permissions
* Adding ISOs and attaching ISOs to VMs - and any other ISO related things
