### ISSUE TITLE
Implement LDAP authentication

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#165]
Since MCVirt has been converted to use built-in user authentication in #163, LDAP support should be added.

Superusers must be able to configure/enable LDAP authentication and must be stored in the MCVirt configuration, which must be synced throughout the cluster.

Users should be able to be added to groups and should be able to be disabled as well.

**Comment by joe-singleton-itdev** [comment]
[python-ldap](https://www.python-ldap.org/) could be useful for this.

**Comment by MatthewJohn** [comment]
I would suggest that we would need to abstract the 'Local storage' part of the user classes into a separate 'Authentication' class structure, which would allow for creating, deleting and authenticating users.
LDAP would require:
Base DN:
Base User search DN
Bind DN (and password) for non-authenticated queries
Group search DN
