### ISSUE TITLE
Perform Pylint checking

### ISSUE THREAD

**Issue by s-knibbs** [ITDevLtd/MCVirt#19]
[Pylint](http://docs.pylint.org/intro.html#what-is-pylint) checks for many things which PEP8 does not, including but not limited to:
* Unused imports
* Unused variables / function arguments
* Dangerous default argument values, e.g. `[]`

This can also be added to the Jenkins build.

**Comment by MatthewJohn** [comment]
We have started doing some work on this in #88 and f7fa186802293eafb20d766789c4b1ad795bfaef
