### ISSUE TITLE
Improve Logging on Pyro4 calls

### ISSUE THREAD

**Issue by Adimote** [ITDevLtd/MCVirt#192]
When the call of a function over RPC fails, the stack trace is lost. 

There are many methods of resolving this, I've found a few of them:
- `sys.excepthook = Pyro4.util.excepthook`, which modifies the default exception handler to also print out Pyro4 exceptions. This may cause problems if we need custom exception hooks later on, but is a single line change
- Override Pyro4's `expose()` method to print the entire stack trace to stderr upon exception.

**Comment by MatthewJohn** [comment]
The expose wrapper now prints a traceback if the method was called over RPC.
Using the new method of calling a method across remote nodes now also formalizes this and provides better logging.
