### ISSUE TITLE
Verify external dependencies across the cluster before performing commands

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#203]
This will apply to quite a few scenarios, such as creating networks, see #201.
Some checks should be:
 * Ensure specified VG exists on all nodes before performing actions that require it.
 * Ensure that there is enough free space in the VG before performing commands

**Comment by joe-singleton-itdev** [comment]
This could be performed on first run.

It could be used to probe libvirt to determine if the 'default' network exists and create in MCVirt if it does not

**Comment by joe-singleton-itdev** [comment]
the method for checking if storage types are available should ensure that the specified VG actually exists (using vgdispaly).
A method for checking free VG space should be created.

During VM creation, a prelimarily check should be performed by the hdd factory to ensure that 1) the storage type is available, 2) it is available on all nodes and 3) there is enough free space available.
