### ISSUE TITLE
Update DRBD hook to support RPC

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#211]

**Comment by joesingo** [comment]
The DRBD hook needs to use a username and password to connect to the. To do this we should create a new user type 'DRBD user'. 

The credentials for the hook to use will be stored in a config file. When the MCVirt daemon starts it will check to see if this config file exists and if a DRBD user exists. If not, then any existing DRBD users are deleted, a new DRBD user is generated and the username and password is stored in the config file.

If the config file does not exist when the hook is run then it should fail silently.

DRBD users do not need to be distributed.

**Comment by MatthewJohn** [comment]
The check can be performed in the __init__ method of the NodeDRBD class (this is created during the start of the Daemon)
