### ISSUE TITLE
Documentation for removing default network no longer works

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#53]
Since MCVirt started storing network configurations in its own configuration files, removing the default network using MCVirt commands is no longer supported as MCVirt has no awareness of the network.

I could see several possibilities of resolving this:

1. Implement sync that can be performed, so that MCVirt looks at all networks in LibVirt and removes any that it is unaware of and creates any that don't exist (this is partially done during the synchronisation when a node is added to a cluster)

2. Change documentation to use virsh to remove default network

3. Add the default network that is provided by libvirt to the default MCVirt configuration file and assume that it exists

**Comment by sjs-itdev** [comment]
The command:

    mcvirt update <VM Name> --remove-network 00:00:00:00:00:00

no longer works:

    Traceback (most recent call last):
      File "/usr/bin/mcvirt", line 41, in <module>
        parser_object.parse_arguments()
      File "/usr/lib/mcvirt/parser.py", line 544, in parse_arguments
        network_adapter_object.delete()
      File "/usr/lib/mcvirt/virtual_machine/network_adapter.py", line 158, in delete
        (self.vm_object.getName(), network))

**Comment by MatthewJohn** [comment]
@sjs-itdev If this is a bug, it is unrelated to this issue. Please create a separate issue for this.
