### ISSUE TITLE
MCVirt should check version numbers during cluster connections

### ISSUE THREAD

**Issue by ndyer** [ITDevLtd/MCVirt#54]
If cluster machines are on different version, it may cause issues. The software should enforce the same version at each end (although it would be good to enable a workflow where upgrades could be done piecemeal whilst keeping VMs running).

**Comment by MatthewJohn** [comment]
A very basic 'check' is already performed when MCVirt connects to a remote node in https://github.com/ITDevLtd/MCVirt/blob/master/source/usr/lib/mcvirt/cluster/remote.py#L389.

This could be replaced with a version check.

MCVirt will need to be aware of it's own version number and will need to add an ``--ignore-version`` that can be run by superusers to allow for the upgrade case.

**Comment by MatthewJohn** [comment]
The version of the installed package can be obtained using:

    import apt_pkg
    
    apt_pkg.init_config()
    apt_pkg.init_system()
    
    cache = apt_pkg.Cache()
    
    for pkg in cache.packages:
      if pkg.current_state is apt_pkg.CURSTATE_INSTALLED and pkg.name == 'mcvirt':
        print pkg.current_ver.ver_str
